//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LN_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Errores
    {
        public int ErrorId { get; set; }
        public string Descripcion { get; set; }
        public string CorreoElectronico { get; set; }
        public string NumeroTelefonico { get; set; }
        public string DetallesError { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<long> IdUsuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
