//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LN_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VidreoUsuario
    {
        public long IdVidreoUsuario { get; set; }
        public long IdUsuario { get; set; }
        public long IdVidreo { get; set; }
        public System.DateTime FechaPago { get; set; }
        public decimal PrecioPago { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Vidreo Vidreo { get; set; }
    }
}
